### PR TITLE
Initial hw2 for Rahil Makadia (makadia2)

### PR DESCRIPTION
**Pull request by rahil-makadia**
- The train script takes about 20 mins to run for all four combinations of replay and target network
- The ablation study is in mean_return_ablation.ipynb, not train_discreteaction_pendulum.py

Feel free tom comment any questions when you go through the review!

### CODE REVIEW

**Comment by Manavvora** [comment]
Hey Rahil, I will review your code.

**Comment by rahil-makadia** [comment]
Hey Manav, I had to turn this hw in early because I am out of town all of next week. I'm gonna keep this PR open and just turn in my dev branch so you can still get your code review in.

**Comment by Manavvora** [comment]
Hey Rahil, sure that sounds good.

**Comment by Manavvora** [comment]
Hey Rahil, a few comments on your code:
1. I really like how you are tracking the time taken by the different variants of DQN. It can help identify which part of the standard DQN algorithm is the most computationally heavy.
2. In your DQN.py file, you initialize the pendulum environment inside the `__init__` method of your DQN class. I would suggest keeping `env` as an input parameter so that you can reuse the same algorithm for different environments. 
3. For your `replay_buffer` you could use something like a **deque** instead of a list. Then, you will not have to worry about checking whether the buffer is full or not when appending an experience to it. But if it doesn't significantly affect the runtime, then there's no need for a change.
4. Your plotting code is really well written and streamlined. Also, all the plots and the gif look great.

**Comment by rahil-makadia** [comment]
apologies for any typos, i'm typing this from my phone...

Thanks for the comments! I didn't know about the deque, I'll def keep that in mind since I'm doing DQN for my final project. And the tip about using env as an argument is good as well. I'll def implement that for m yproject

**Pull request merged**
